package com.eva.bluetoothterminalapp.domain.bluetooth_le.enums

enum class BLEPermission {

	PERMISSION_READ,
	PERMISSION_READ_ENCRYPTED,
	PERMISSION_READ_ENCRYPTED_MITM,
	PERMISSION_WRITE,
	PERMISSION_WRITE_ENCRYPTED,
	PERMISSION_WRITE_ENCRYPTED_MITM,
	PERMISSION_WRITE_SIGNED,
	PERMISSION_WRITE_SIGNED_MITM,
	PERMISSION_UNKNOWN,

}